### ISSUE TITLE
Leakage of result from previous run

### ISSUE THREAD

**Issue by dennismphil** [billpatrianakos/saml2js#4]
# Description

Ran into an issue using this library. If we invoke this twice, the result of the second instance is from the first invocation. 

![code](https://user-images.githubusercontent.com/4141366/78655794-57f1db00-787b-11ea-8bcc-d36ebedb8c1e.png)

This is because [profile](https://github.com/billpatrianakos/saml2js/blob/master/index.js#L10) is a global variable

```js
var xmldom    = require('xmldom'),
    xpath     = require('xpath'),
    _         = require('lodash'),
    profile   = {};  // <------------------------ Culprit: Global Variable

// Saml2js
// -------
// Constructor function. Saves a copy
// of the raw SAML you pass to it and 
// a copy that's parsed into a JS object.
//
// `response` [String] - A SAML response string
function Saml2js (response) {
  this.rawSaml    = response;
  this.parsedSaml = this.parse(response);
}
```

**Comment by TheFabiocool** [comment]
Can confirm this happens, the fix is as simple as setting `profile` inside the function, and start calling `this.profile` down the line.
However, this issue is now 7 months old and the maintainer doesn't seem to want to bother fixing anything else besides his readme.md so I'd say this project is dead.
Even worse, is that we were using this in production for 1 week.

**Comment by meramjanam** [comment]
Function definition "Saml2js.prototype.parse", the profile variable is globally declared should be declared as function instance member variable because of this if function will called the profile variable initiated inside the function then it will destroy when function scope destroy. So the memory leak will stop.

Saml2js.prototype.parse = function(saml) {
  **let profile = {}**
  var xml       = new Buffer(saml, 'base64').toString('ascii'),
      doc       = new xmldom.DOMParser().parseFromString(xml);

  var attributes = xpath.select('//*[local-name() = "AttributeStatement"]/*', doc);
  attributes.forEach(function(attribute){
    var name = xpath.select('string(@Name)', attribute);    
    profile[_.camelCase(name)] = xpath.select('string(*[local-name() = "AttributeValue"]/text())', attribute);
  });

  return profile;
};

NOTE: Please verify with you module because it is critical.

**Comment by billpatrianakos** [comment]
Yikes. I will try to update this but I'm not sure if I can continue to support this project. I originally made it for a use-case where I'd only need one profile. It was for interfacing with the Healthcare.gov private API. If someone wants to submit a pull request that would speed the process greatly. In time meantime, I have this on my radar and I'll get to it ASAP. Thank you, everyone, for catching and verifying the issue.
